# -------------------------------
# Статические настройки PostgreSQL
# -------------------------------

# Загружаемые библиотеки (обязательно до создания расширений)
shared_preload_libraries = 'timescaledb,pg_stat_statements'

# Подключения и память
max_connections = 32
shared_buffers = 1GB

# Логирование
log_min_duration_statement = 1000
log_line_prefix = '%t [%p]: user=%u, db=%d, app=%a, client=%h '

# Дополнительные рекомендуемые статические параметры
effective_cache_size = 3GB # примерно 50-75% от ОЗУ
wal_buffers = 16MB # TODO Уточнить на что влияет
checkpoint_completion_target = 0.9 # TODO Уточнить на что влияет

listen_adresses = '*'